#!/bin/bash
# This file is part of Rodent Linux
# Copyright 2015-2016 Emil Renner Berthing

set -e

readonly arch="$1"
shift

. "$RODENT/settings"

usage() {
  echo 'halp!'
}

while true; do
  case "$1" in
  -s) SYSROOT="$2"; shift 2;;
  -h|help)
    usage
    exit 0;;
  *) break;;
  esac
done
[[ -n "$SYSROOT" ]] || SYSROOT="$RODENT/sysroot.$arch"

if [[ ! -d "$SYSROOT" ]]; then
  echo "Sysroot '$SYSROOT' not found."
  exit 1
fi

while read -r pkg rest; do
  echo "=== $pkg ==="
  awk -F'\t' '$2=="d"{print $1 "/"};$2=="f"{print $1};$2=="l"{print $1 " -> " $6}' "$SYSROOT/#/${pkg/=/-}.files"
done < <(grep "^$1" "$SYSROOT/#/installed")

# vim: set ft=sh ts=2 sw=2 et:
