#!/bin/bash
# This file is part of Rodent Linux
# Copyright 2015 Emil Renner Berthing

set -e

if [[ "$1" = 'help' ]]; then
  echo 'halp!'
  exit 0
fi

while true; do
  case "$1" in
  -s) SYSROOT="$2"; shift 2;;
  *) break;;
  esac
done
[[ -n "$SYSROOT" ]] || SYSROOT="$ROOT/sysroot.$ARCH"

if [[ ! -d "$SYSROOT" ]]; then
  echo "Sysroot '$SYSROOT' not found."
  exit 1
fi

while read -r pkg rest; do
  echo "=== $pkg ==="
  awk -F'\t' '$2=="d"{print $1 "/"};$2=="f"{print $1};$2=="l"{print $1 " -> " $6}' "$SYSROOT/#/${pkg/=/-}.files"
done < <(grep "^$1" "$SYSROOT/#/installed")

# vim: set ft=sh ts=2 sw=2 et:
