#!/bin/bash
# This file is part of Rodent Linux
# Copyright 2015-2016 Emil Renner Berthing

set -e

usage() {
  echo 'halp!'
}

while true; do
  case "$1" in
  -h|help)
    usage
    exit 0;;
  *) break;;
  esac
done

if [[ -z "$1" ]]; then
  echo 'What do you want to install?'
  exit 1
fi

for i in "$RODENT/cache/host/$1"-*.host.tar.xz; do
  file="$i"
done

if [[ ! -f "$file" ]]; then
  echo "Could not find cache/host/${1}-*.host.tar.xz"
  exit 1
fi

cd "$RODENT"
echo "Unpacking ${file}.."
tar -xmvf "$file"

# vim: set ft=sh ts=2 sw=2 et:
