#!/bin/bash
# This file is part of Rodent Linux
# Copyright 2015-2016 Emil Renner Berthing

set -e

readonly arch="$1"
shift

. "$RODENT/settings"

usage() {
  echo 'halp!'
}

while true; do
  case "$1" in
  -s) SYSROOT="$2"; shift 2;;
  -h|help)
    usage
    exit 0;;
  *)  break;;
  esac
done

if [[ $# = 0 ]]; then
  echo 'Install what?'
  usage
  exit 1
fi

[[ -n "$SYSROOT" ]] || SYSROOT="$RODENT/sysroot.$arch"

. "$RODENT/lib/ro/download.sh"
. "$RODENT/lib/ro/hooks.sh"
. "$RODENT/lib/ro/deps_install.sh"

sysroot_init
deps_calculate "$@"
deps_ask
deps_download
hooks_remove_files
deps_install
hooks_run

# vim: set ft=sh ts=2 sw=2 et:
