#!/bin/bash
# This file is part of Rodent Linux
# Copyright 2015-2016 Emil Renner Berthing

set -e

readonly arch="$1"
shift

. "$RODENT/settings"

usage() {
  echo 'halp!'
}

while true; do
  case "$1" in
  -s) SYSROOT="$2"; shift 2;;
  -h|help)
    usage
    exit 0;;
  *) break;;
  esac
done
[[ -z "$1" ]]       || SYSROOT="$1"
[[ -n "$SYSROOT" ]] || SYSROOT="$RODENT/sysroot.$arch"

if [[ ! -d "$SYSROOT" ]]; then
  echo "Sysroot '$SYSROOT' not found."
  exit 1
fi

awk -F'\t' '{print $1}' "$SYSROOT/#/installed"

# vim: set ft=sh ts=2 sw=2 et:
