#!/bin/bash
# This file is part of Rodent Linux
# Copyright 2015-2016 Emil Renner Berthing

set -e

readonly arch="$1"
readonly recipe="$2"
readonly dependencies="$3"
readonly extract="$4"

. "$RODENT/lib/ro/make-defaults.sh"
. "$RODENT/settings"

srcdir="${recipe%/*}"
base="${srcdir##*/}"
cd "$srcdir"

. "$recipe"
. "$RODENT/lib/ro/download.sh"

if [[ "$extract" -gt 0 ]]; then
  n="${#sources[@]}"
  for ((i=0;i<n;i++)); do
    url="${sources[$i]}"
    sha1="${sha1sum[$i]}"

    while true; do
      case "${url%%:*}" in
      noextract) url="${url#*:}";;
      *) break;;
      esac
    done

    file="${url##*/}"
    file="${file%%\?*}"
    check_or_download "$srcdir" "$file" "$sha1" "$url"
  done
fi

if [[ -n "$BUILDDIR" ]]; then
  builddir="$BUILDDIR/$base/$arch"
else
  builddir="$srcdir/$arch"
fi
[[ "$extract" -eq 0 ]] || rm -rf "$builddir"
mkdir -p "$builddir"
[[ -n "$SYSROOT" ]] || SYSROOT="$builddir/sysroot"

if [[ "$dependencies" -gt 0 ]]; then
  . "$RODENT/lib/ro/hooks.sh"
  . "$RODENT/lib/ro/deps_install.sh"
  sysroot_init
  deps_calculate "${makedepends[@]}"
  deps_download
fi

# vim: set ft=sh ts=2 sw=2 et:
