#!/bin/bash
# This file is part of Rodent Linux
# Copyright 2016 Emil Renner Berthing

set -e

readonly -a archs=(${1//,/ })
shift

. "$RODENT/settings"

usage() {
  echo 'halp!'
}

while true; do
  case "$1" in
  -h|help)
    usage
    exit 0;;
  *) break;;
  esac
done

if [[ -z "$1" ]]; then
  usage
  exit 1
fi

. "$RODENT/lib/ro/makerepo.sh"

cd "$1"
for arch in "${archs[@]}"; do
  makerepo "$arch"
done

# vim: set ft=sh ts=2 sw=2 et:
