#!/bin/bash
# This file is part of Rodent Linux
# Copyright 2015-2016 Emil Renner Berthing

set -e
export USER=root

readonly arch="$1"
readonly recipe="$2"
readonly builddir="$3"

. "$RODENT/lib/ro/make-defaults.sh"
. "$RODENT/settings"

srcdir="${recipe%/*}"
pkgdir="$builddir/pkg"
base="${srcdir##*/}"
cd "$srcdir"

. "$recipe"
[[ ${#parts[@]} -gt 0 ]] || parts=($base)

echo 'Packaging..'
cd "$builddir"
set -x
package
set +x

cd "$pkgdir"
echo -n 'Recording metadata.. '
find -P . -mindepth 1 -printf '%P\n' | sort -u | while read -r path; do
  if [[ -L "$path" ]]; then
    stat --printf "$path\tl\t%a\t%u\t%g\t" "$path"
    readlink "$path"
  elif [[ -f "$path" ]]; then
    sha1="$(sha1sum "$path")"
    stat --printf "$path\tf\t%a\t%u\t%g\t${sha1%% *}" "$path"
    TYPE="$(file -b "$path")"
    TYPE="${TYPE#setuid }"
    TYPE="${TYPE#setuid, }"
    TYPE="${TYPE#setgid }"
    if [[ "${TYPE%% *}" = 'ELF' ]]; then
      echo -e '\tstrip'
    else
      echo
    fi
  elif [[ -d "$path" ]]; then
    stat --printf "$path\td\t%a\t%u\t%g\n" "$path"
  elif [[ -c "$path" ]]; then
    stat --printf "$path\tc\t%a\t%u\t%g\t%t\t%T\n" "$path"
  elif [[ -b "$path" ]]; then
    stat --printf "$path\tb\t%a\t%u\t%g\t%t\t%T\n" "$path"
  else
    echo "What is '$path'?"
    exit 1
  fi
done > ../files
echo 'done.'

# vim: set ts=2 sw=2 et:
