#!/bin/bash
# This file is part of Rodent Linux
# Copyright 2015 Emil Renner Berthing

set -e

if [[ "$1" = 'help' ]]; then
  echo 'halp!'
  exit 0
fi

while true; do
  case "$1" in
  -s) SYSROOT="$2"; shift 2;;
  -d) NODEPS=1; shift;;
  *) break;;
  esac
done
export PKG="$1"
[[ -n "$SYSROOT" ]] || SYSROOT="$ROOT/sysroot.$ARCH"

if [[ ! -d "$SYSROOT" ]]; then
  echo "Sysroot '$SYSROOT' not found."
  exit 1
fi

cd "$SYSROOT"

pkgs=()
while read -r pkg; do
  pkgs+=("$pkg")
done < <(
  for i in "$@"; do echo "$i"; done \
    | awk -f "$ROOT/lib/ro/graphlib.awk" -f "$ROOT/lib/ro/find-pkgs.awk" - '#/installed'
)
for i in "${pkgs[@]}"; do
  case "$i" in
  *' '*) echo "Which of these do you want? $i"; err=1;;
  *=*)   ;;
  *)     echo "Package '$i' not found."; err=1;;
  esac
done
[[ -z "$err" ]] || exit 1

if [[ -z "$NODEPS" ]]; then
  if ! for pkg in "${pkgs[@]}"; do echo "$pkg"; done \
       | awk -f "$ROOT/lib/ro/graphlib.awk" -f "$ROOT/lib/ro/remove-deps.awk" - \#/installed
  then
    echo 'Aborting.'
    exit 1
  fi
fi

echo 'Removing'
for pkg in "${pkgs[@]}"; do
  echo "* $pkg"
done

set +e

echo 'Deleting files'
awk -F'\t' '$2=="f"||$2=="d"||$2=="l"{print $1}' \#/*.files | sort -u > '#/allfiles'
for pkg in "${pkgs[@]}"; do
  file="#/${pkg/=/-}.files"
  echo "- rm    $file"
  rm "$file"
done
awk -F'\t' '$2=="f"||$2=="d"||$2=="l"{print $1}' \#/*.files \
  | sort -u \
  | comm -23 '#/allfiles' - \
  | sort -r \
  | while read -r i; do
  if [[ -d "$i" ]]; then
    echo "- rmdir $i"
    rmdir "$i"
  else
    echo "- rm    $i"
    rm "$i"
  fi
done
for pkg in "${pkgs[@]}"; do echo "$pkg"; done \
  | awk -f "$ROOT/lib/ro/remove-installed.awk" - '#/installed' > '#/installed.new'
mv -f '#/installed.new' '#/installed'
rm '#/allfiles'

# vim: set ft=sh ts=2 sw=2 et:
