#!/bin/bash
# This file is part of Rodent Linux
# Copyright 2015-2016 Emil Renner Berthing

set -e

readonly arch="$1"
shift

. "$RODENT/settings"

usage() {
  echo 'halp!'
}

while true; do
  case "$1" in
  -s) SYSROOT="$2"; shift 2;;
  -d) NODEPS=1; shift;;
  -h|help)
    usage
    exit 0;;
  *) break;;
  esac
done
export PKG="$1"
[[ -n "$SYSROOT" ]] || SYSROOT="$RODENT/sysroot.$arch"

if [[ ! -d "$SYSROOT" ]]; then
  echo "Sysroot '$SYSROOT' not found."
  exit 1
fi

cd "$SYSROOT"

pkgs=()
while read -r pkg; do
  pkgs+=("$pkg")
done < <(
  for i in "$@"; do echo "$i"; done \
    | awk -f "$RODENT/lib/ro/graphlib.awk" -f "$RODENT/lib/ro/find-pkgs.awk" - '#/installed'
)
for i in "${pkgs[@]}"; do
  case "$i" in
  *' '*) echo "Which of these do you want? $i"; err=1;;
  *=*)   ;;
  *)     echo "Package '$i' not found."; err=1;;
  esac
done
[[ -z "$err" ]] || exit 1

if [[ -z "$NODEPS" ]]; then
  if ! for pkg in "${pkgs[@]}"; do echo "$pkg"; done \
       | awk -f "$RODENT/lib/ro/graphlib.awk" -f "$RODENT/lib/ro/remove-deps.awk" - \#/installed
  then
    echo 'Aborting.'
    exit 1
  fi
fi

remove_files() {
  local i

  awk -F'\t' '$2=="f"||$2=="d"||$2=="l"{print $1}' \#/*.files | sort -u > '#/allfiles'
  for i in "$@"; do
    #echo "- rm    $i"
    rm "$i"
  done
  awk -F'\t' '$2=="f"||$2=="d"||$2=="l"{print $1}' \#/*.files \
    | sort -u \
    | comm -23 '#/allfiles' - \
    | sort -r \
    | while read -r i; do
    if [[ -d "$i" ]]; then
      #echo "- rmdir $i"
      rmdir "$i"
    else
      #echo "- rm    $i"
      rm "$i"
    fi
  done
  rm '#/allfiles'
}

echo 'Removing'
files=()
for pkg in "${pkgs[@]}"; do
  echo "* $pkg"
  files+=("#/${pkg/=/-}.files")
done

echo -n 'Deleting files.. '
remove_files "${files[@]}"
for pkg in "${pkgs[@]}"; do echo "$pkg"; done \
  | awk -f "$RODENT/lib/ro/remove-installed.awk" - '#/installed' > '#/installed.new'
mv -f '#/installed.new' '#/installed'
echo 'done.'

# vim: set ft=sh ts=2 sw=2 et:
