#!/bin/bash
# This file is part of Rodent Linux
# Copyright 2015-2016 Emil Renner Berthing

set -e

readonly arch="$1"
shift

# Architecture specific defaults
case $arch in
armv7hl) COMPRESSION='xz -Xbcj armthumb';;
rpi)     COMPRESSION='xz -Xbcj arm';;
quark)   COMPRESSION='xz -Xbcj x86';;
mips)    COMPRESSION='xz';;
mipsel)  COMPRESSION='xz';;
*)
  echo "Unknown architecture '$arch'"
  exit 1
  ;;
esac

. "$RODENT/lib/ro/make-defaults.sh"
. "$RODENT/settings"

usage() {
  echo 'halp!'
}

while true; do
  case "$1" in
  -s) SYSROOT="$(readlink -f "$2")"; shift 2;;
  -o) OUTPUT="$(readlink -f "$2")";  shift 2;;
  -c) COMPRESSION="$2";              shift 2;;
  -h|help)
    usage
    exit 0;;
  *) break;;
  esac
done

[[ -n "$SYSROOT" ]] || SYSROOT="$RODENT/sysroot.$arch"
[[ -n "$OUTPUT"  ]] || OUTPUT="$(readlink -f ./image.sqfs)"

if ! command -v "${host}-strip" >/dev/null 2>&1; then
  if "$RODENT/bin/${host}-strip" -h >/dev/null 2>&1; then
    mkdir -p "$RODENT/tools/bin"
    ln "$RODENT/bin/${host}-strip" "$RODENT/tools/bin/${host}-strip"
  else
    echo "Could not find suitable ${host}-strip in \$PATH."
    echo "Try ./ro host-make binutils && ./ro host-install ${arch}-binutils"
    exit 1
  fi
fi

if [[ $# -gt 0 ]]; then
  . "$RODENT/lib/ro/download.sh"
  . "$RODENT/lib/ro/hooks.sh"
  . "$RODENT/lib/ro/deps_install.sh"
  sysroot_init
  deps_calculate "$@"
  deps_ask
  deps_download
  hooks_remove_files
  deps_install
  hooks_run
elif [[ ! -d "$SYSROOT" ]]; then
    echo "No sysroot found in '$SYSROOT'."
    exit 1
fi

cd "$SYSROOT/#"
awk -F'\t' '$1!~/^#/{print}' *.files \
  | sort -u \
  > "$RODENT/image.files"

mkdir "${SYSROOT}.tmp"
cd "${SYSROOT}.tmp"
awk -F'\t' '{print $1;print $2;print $6;print $7}' "$RODENT/image.files" | while read -r path; do
  read -r type
  read -r extra
  read -r strip
  case "$type" in
  d) mkdir -p "$path";;
  l) ln -s "$extra" "$path";;
  f)
    if [[ "$strip" = 'strip' ]]; then
      ${host}-strip --strip-unneeded -o "$path" "$SYSROOT/$path"
    else
      ln "$SYSROOT/$path" "$path"
    fi
    ;;
  esac
done

awk -f "$RODENT/lib/ro/squash-pseudofile.awk" "$RODENT/image.files" \
  > "$RODENT/pseudofile"

mksquashfs . "$OUTPUT" \
  -pf "$RODENT/pseudofile" \
  -comp $COMPRESSION \
  -no-exports -no-xattrs -noappend

rm -rf "${SYSROOT}.tmp"

# vim: set ft=sh ts=2 sw=2 et:
