#!/bin/bash
# This file is part of Rodent Linux
# Copyright 2015 Emil Renner Berthing

set -e

usage() {
  echo 'halp!'
}

if [[ "$1" == help ]]; then
  usage
  exit 0
fi

[[ -z "$1" ]] || IMAGE="$1"
[[ -n "$IMAGE" ]] || IMAGE="$ROOT/image.sqfs"

case "$ARCH" in
armv7hl)
  cmd=(qemu-system-arm -machine vexpress-a9 -smp 4
    -dtb "$ROOT/lib/vexpress-v2p-ca9.dtb"
  )
  console='console=ttyAMA0'
  nic='model=lan9118'
  virtio_scsi='virtio-scsi-device'
  virtio_9p='virtio-9p-device'
  ;;
quark)
  #-cpu qemu32,+pae,+pbe,+nx,+smep,-mce,-sep,-pge,-cmov,-fxsr,-mmx,-sse,-sse2,-pni,-popcnt
  cmd=(qemu-system-quark -machine pc -smp 1
    -cpu pentium,+pae,+pbe,+nx,+smep,-mce,-mmx
    -smbios type=0,uefi=on
  )
  console='console=ttyS0'
  nic='model=virtio'
  virtio_scsi='virtio-scsi-pci'
  virtio_9p='virtio-9p-pci'
  ;;
*)
  echo "Unknown architecture '$ARCH'."
  exit 1;;
esac

cmd+=(
  -m 512
  -nographic
  -kernel "$ROOT/lib/kernel.$ARCH"
  -append "$console root=/dev/sda ro rootwait"
  -net nic,$nic
  -net user,net=192.168.7.0/24,dhcpstart=192.168.7.16,hostname=guest,hostfwd=tcp::2222-:22
  -fsdev local,id=rodent,path="$ROOT",security_model=none,readonly
  -device $virtio_9p,fsdev=rodent,mount_tag=rodent
)

if [[ -f "$ROOT/initrd.cpio" ]]; then
  cmd+=(-initrd "$ROOT/initrd.cpio")
fi

if [[ -f "$IMAGE" ]]; then
  cmd+=(
    -device $virtio_scsi,id=scsi
    -device scsi-hd,drive=root
    -drive if=none,id=root,format=raw,readonly,file="$IMAGE"
  )
fi

export QEMU_AUDIO_DRV=none

set -x
exec "${cmd[@]}"

# vim: set ft=sh ts=2 sw=2 et:
