#!/bin/bash
# This file is part of Rodent Linux
# Copyright 2015-2016 Emil Renner Berthing

set -e

readonly arch="$1"
shift

. "$RODENT/settings"

usage() {
  echo 'halp!'
}

while true; do
  case "$1" in
  -h|help)
    usage
    exit 0;;
  *) break;;
  esac
done

[[ -z "$1"     ]] || IMAGE="$1"
[[ -n "$IMAGE" ]] || IMAGE="$RODENT/image.sqfs"

case $arch in
armv7hl)
  cmd=(qemu-system-arm -machine vexpress-a9 -smp 4
    -dtb "$RODENT/lib/vexpress-v2p-ca9.dtb"
  )
  console='console=ttyAMA0'
  nic='model=lan9118'
  virtio_scsi='virtio-scsi-device'
  virtio_9p='virtio-9p-device'
  ;;
quark)
  #-cpu qemu32,+pae,+pbe,+nx,+smep,-mce,-sep,-pge,-cmov,-fxsr,-mmx,-sse,-sse2,-pni,-popcnt
  cmd=(qemu-system-quark -machine pc
    -cpu pentium,+pae,+pbe,+nx,+smep,-mce,-mmx
    -smp 1 -m 512
    -smbios type=0,uefi=on
  )
  console='console=ttyS0'
  nic='model=virtio'
  virtio_scsi='virtio-scsi-pci'
  virtio_9p='virtio-9p-pci'
  ;;
*)
  echo "Unknown architecture '$arch'."
  exit 1;;
esac

cmd+=(
  -nographic
  -kernel "$RODENT/lib/kernel.$arch"
  -append "$console root=/dev/sda ro rootwait"
  -net nic,$nic
  -net user,net=192.168.7.0/24,dhcpstart=192.168.7.16,hostname=guest,hostfwd=tcp::2222-:22
  -fsdev local,id=rodent,path="$RODENT",security_model=none,readonly
  -device $virtio_9p,fsdev=rodent,mount_tag=rodent
)

if [[ -f "$RODENT/initrd.cpio" ]]; then
  cmd+=(-initrd "$RODENT/initrd.cpio")
fi

if [[ -f "$IMAGE" ]]; then
  cmd+=(
    -device $virtio_scsi,id=scsi
    -device scsi-hd,drive=root
    -drive if=none,id=root,format=raw,readonly,file="$IMAGE"
  )
fi

export QEMU_AUDIO_DRV=none

set -x
exec "${cmd[@]}"

# vim: set ft=sh ts=2 sw=2 et:
