#!/bin/bash
# This file is part of Rodent Linux
# Copyright 2015-2016 Emil Renner Berthing

set -e

readonly -a archs=(${1//,/ })
shift

. "$RODENT/settings"

usage() {
  echo 'halp!'
}

while true; do
  case "$1" in
  -h|help)
    usage
    exit 0;;
  *) break;;
  esac
done

. "$RODENT/lib/ro/download.sh"

for arch in "${archs[@]}"; do
  for i in "${REPOS[@]}"; do
    name="${i%%:*}"
    url="${i#*:}"
    proto="${url%%:*}"

    if [[ "$proto" = http || "$proto" = https ]]; then
      mkdir -p "$RODENT/cache/$name"
      download "$url/repo.${arch}.xz" "$RODENT/cache/$name/repo.${arch}.xz"
    fi
  done
done

# vim: set ft=sh ts=2 sw=2 et:
