#!/bin/bash
# This file is part of Rodent Linux
# Copyright 2015-2016 Emil Renner Berthing

set -e

readonly arch="$1"
shift

. "$RODENT/settings"

usage() {
  echo 'halp!'
}

while true; do
  case "$1" in
  -s) SYSROOT="$2"; shift 2;;
  -h|help)
    usage
    exit 0;;
  *) break;;
  esac
done
[[ -z "$1" ]]       || SYSROOT="$1"
[[ -n "$SYSROOT" ]] || SYSROOT="$RODENT/sysroot.$arch"

if [[ ! -d "$SYSROOT" ]]; then
  echo "Sysroot '$SYSROOT' not found."
  exit 1
fi

cd "$SYSROOT"
echo 'Checking dependencies'
awk -f "$RODENT/lib/ro/graphlib.awk" -f "$RODENT/lib/ro/verify-deps.awk" \#/installed

echo 'Checking file lists'
find '#' -mindepth 1 -maxdepth 1 -name '*.files' -printf '%P\n' \
  | awk -f "$RODENT/lib/ro/verify-lists.awk" - \#/installed

echo 'Checking path conflicts'
awk -f "$RODENT/lib/ro/path-conflicts.awk" \#/installed || true

echo 'Checking new/removed files'
find . -mindepth 1 -printf '%P\n' \
  | awk -f "$RODENT/lib/ro/verify-files.awk" - \#/*.files

echo 'Checking symlinks'
awk -F'\t' '$2=="l"{print $1;print $6}' \#/*.files \
  | while read -r file; do
  read -r target
  if [[ "$(readlink "$file")" = "$target" ]]; then
    continue
  fi

  echo "- $file -> $target"
  echo "+ $file -> $(readlink "$file")"
done

echo 'Checking file content'
awk -F'\t' '$2=="f"{print $6 "  " $1}' \#/*.files \
  | sha1sum -c --strict --quiet

# vim: set ft=sh ts=2 sw=2 et:
