#!/bin/bash
# This file is part of Rodent Linux
# Copyright 2015-2016 Emil Renner Berthing

export RODENT="$(dirname "$(readlink -f "$0")")"
export PATH="$RODENT/tools/bin:$PATH"
export LD_LIBRARY_PATH="$RODENT/tools/lib"
export LC_COLLATE=C

if [[ ! -f "$RODENT/settings" ]]; then
  echo "No settings file found."
  echo "Please copy settings.proto to settings."
  exit 1
fi

. "$RODENT/settings"

usage() {
  echo 'usage: ro [-a ARCH] <command>'
  echo
  echo '  update       - update repo information'
  echo '  install      - install package to sysroot'
  echo '  remove       - uninstall package from sysroot'
  echo '  verify       - verify sysroot'
  echo '  list         - show installed packages in sysroot'
  echo '  leaves       - show packages not required by any other in sysroot'
  echo '  files        - show files in an installed packages'
  echo '  make         - build new package'
  echo '  makerepo     - create repo metadata from packages'
  echo '  host-make    - build new host package'
  echo '  host-install - install host package'
  echo '  squash       - build squashfs image'
  echo '  initrd       - build initramfs cpio archive'
  echo '  test         - run squashfs image in qemu'
  echo
}

while true; do
  arg="$1"
  shift
  case "$arg" in
  -a) ARCH="$1"; shift;;
  up|update)
    exec "$RODENT/lib/ro/update" "$ARCH" "$@";;
  in|install)
    exec "$RODENT/lib/ro/install" "${ARCH%%,*}" "$@";;
  rm|remove)
    exec "$RODENT/lib/ro/remove" "${ARCH%%,*}" "$@";;
  ver|verify)
    exec "$RODENT/lib/ro/verify" "${ARCH%%,*}" "$@";;
  ls|list)
    exec "$RODENT/lib/ro/list" "${ARCH%%,*}" "$@";;
  leaves)
    exec "$RODENT/lib/ro/leaves" "${ARCH%%,*}" "$@";;
  files)
    exec "$RODENT/lib/ro/files" "${ARCH%%,*}" "$@";;
  mk|make)
    exec "$RODENT/lib/ro/make" "$ARCH" "$@";;
  mr|makerepo)
    exec "$RODENT/lib/ro/makerepo" "$ARCH" "$@";;
  hin|host-install)
    exec "$RODENT/lib/ro/host-install" "$@";;
  hmk|host-make)
    exec "$RODENT/lib/ro/host-make" "${ARCH%%,*}" "$@";;
  sq|squash)
    exec "$RODENT/lib/ro/squash" "${ARCH%%,*}" "$@";;
  initrd)
    exec "$RODENT/lib/ro/initrd" "${ARCH%%,*}" "$@";;
  test)
    exec "$RODENT/lib/ro/test" "${ARCH%%,*}" "$@";;
  -h|help)
    usage
    exit 0
    ;;
  *)
    usage
    exit 1
    ;;
  esac
done

# vim: set ft=sh ts=2 sw=2 et:
