#!/bin/sh

set -e

num_present_cpus() {
  local num_cpus=0
  local line
  read -r line < /sys/devices/system/cpu/present
  local i
  for i in ${line//,/ }; do
    case $i in
    *-*) num_cpus=$((num_cpus + ${i#*-} - ${i%-*} + 1));;
    *)   num_cpus=$((num_cpus + 1));;
    esac
  done
  echo $num_cpus
}

dev=${2#/dev/}
case $1 in
up)
  # get the amount of memory in the machine (in 4k blocks)
  while read -r line; do
    if [[ "${line%%:*}" = 'MemTotal' ]]; then
      size="${line#MemTotal:}"
      size="${size% kB}"
      break
    fi
  done < /proc/meminfo
  if [[ -z "$size" ]]; then
    echo 'Error parsing /proc/meminfo.' >&2
    exit 1
  fi
  size=$(((size / 4) * 4096))

  # initialize the device
  num_present_cpus > /sys/block/$dev/max_comp_streams
  echo $size > /sys/block/$dev/disksize
  #echo $((size / 2)) > /sys/block/$dev/mem_limit
  mkswap /dev/$dev
  ;;

down)
  echo 1 > /sys/block/$dev/reset
  ;;
esac

# vim: set ts=2 sw=2 et:
