#!/bin/bash

configfs='/sys/kernel/config'
gadget='gadget1'
udc='musb-hdrc.0.auto'

manufacturer='Texas Instruments'
product='BeagleBone'

maxpower=120

func='mass_storage.0 acm.0 rndis.0 eem.0'
func_mass_storage_0_lun_0_file='/dev/mmcblk0'
func_rndis_0_dev_addr="$(sed 's/\(..\)\(..\)\(..\)\(..\)\(..\).*/02:\1:\2:\3:\4:\5/' /etc/machine-id)"
func_eem_0_dev_addr="$(sed 's/\(..\)\(..\)\(..\)\(..\)\(..\).*/06:\1:\2:\3:\4:\5/' /etc/machine-id)"

conf='rndis eem'
conf_rndis_desc='RNDIS + ACM + Mass Storage'
conf_rndis_func='mass_storage.0 acm.0 rndis.0'
conf_eem_desc='EEM + ACM + Mass Storage'
conf_eem_func='mass_storage.0 acm.0 eem.0'

case "$1" in
up)
  set -e
  #modprobe libcomposite


  mkdir "$configfs/usb_gadget/$gadget"
  cd "$configfs/usb_gadget/$gadget"

  for f in $func; do
    mkdir "functions/$f"
    case ${f%%.*} in
    mass_storage)
      tmp="func_${f//./_}_lun_0_file"
      tmp="${!tmp}"
      [[ -z "$tmp" ]] || echo "$tmp" > "functions/$f/lun.0/file"
      ;;
    ecm|eem|rndis)
      for file in dev_addr host_addr; do
        tmp="func_${f//./_}_$file"
        tmp="${!tmp}"
        [[ -z "$tmp" ]] || echo "$tmp" > "functions/$f/$file"
      done
      ;;
    esac
  done

  i=0
  for c in $conf; do
    i=$(($i+1))

    mkdir "configs/$c.$i"
    [[ -z "$maxpower" ]] || echo "$maxpower" > "configs/$c.$i/MaxPower"
    mkdir "configs/$c.$i/strings/0x409"
    tmp="conf_${c}_desc"
    tmp="${!tmp}"
    [[ -z "$tmp" ]] || echo "$tmp" > "configs/$c.$i/strings/0x409/configuration"

    tmp="conf_${c}_func"
    for f in ${!tmp}; do
      ln -s "functions/$f" "configs/$c.$i"
    done
  done

  mkdir strings/0x409
  echo "$manufacturer" > strings/0x409/manufacturer
  echo "$product" > strings/0x409/product
  cat /etc/machine-id > strings/0x409/serialnumber

  echo '0x04e8' > idVendor
  echo '0x0106' > idProduct

  echo "$udc" > UDC
  ;;
down)
  cd "$configfs/usb_gadget/$gadget"
  echo > UDC
  rmdir strings/*
  rmdir configs/*/strings/*
  find configs/* -maxdepth 1 -type l -delete
  rmdir configs/*
  rmdir functions/*
  cd ..
  rmdir "$gadget"
  ;;
*)
  echo 'up or down?' >&2
  exit 1
  ;;
esac
